# Generated by Django 3.1.3 on 2021-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=60)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
